modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GPLv3"
[[mods]] #mandatory
modId="norandomdropposition" #mandatory
version="1.20.1-1.0.0" #mandatory
displayName="no random drop position" #mandatory
authors="Rinko1231" #optional
description="no more random drop position and velocity offset"
configBackground="minecraft:textures/block/bricks.png"

[[dependencies.norandomdropposition]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.norandomdropposition]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
